version: '3.8'

services:
  whisperui:
    build: .
    ports:
      - "8502:8501"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              count: 1
