version: '3.8'

services:
  whisperui:
    build: .
    #image: ghcr.io/ninanor/whisperui:latest
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    restart: unless-stopped
