services:
  app:
    build:
      context: .
    command: uv run streamlit run app.py
    ports:
      - "8501:8501"
    develop:
      watch:
        # Sync the working directory with the `/app` directory in the container
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./pyproject.toml
