[project]
name = "whisperui"
version = "0.1.0"
description = "AWhisper UI"
authors = [
    {name = "Benjamin Cretois", email = "benjamin.cretois@nina.no"},
    {name = "Francesco Frassinelli", email = "francesco.frassinelli@nina.no"},
]
requires-python = ">=3.10"
dependencies = [
    "openai-whisper>=20250625",
    "streamlit>=1.47.1",
]
